package sharedwallet

import (
	"context"
	"fmt"
	"math/big"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
	"cloud.google.com/go/firestore"

	"drexa/internal/config"
	"drexa/internal/tatum"
)

// ─── Interfaces ──────────────────────────────────────────────────────────────

type WalletService interface {
	CreateUserWallet(ctx context.Context, userId, currency string) (*Wallet, error)
	GetBalance(ctx context.Context, userId, currency string) (string, string, error)
	ProcessDeposit(ctx context.Context, payload WebhookPayload) error
	RequestWithdrawal(ctx context.Context, req WithdrawalRequest) (*Transaction, error)
}

type InternalTransferService interface {
	Transfer(ctx context.Context, req InternalTransferRequest) (*Transaction, error)
}

// ─── DTOs ────────────────────────────────────────────────────────────────────

type WebhookPayload struct {
	Address       string `json:"address"`
	Amount        string `json:"amount"`
	Asset         string `json:"asset"`
	BlockNumber   int    `json:"blockNumber"`
	Confirmations int    `json:"confirmations"`
	TxId          string `json:"txId"`
	Type          string `json:"type"` // "native" etc.
}

type WithdrawalRequest struct {
	UserID    string `json:"user_id"`
	Currency  string `json:"currency"`
	Amount    string `json:"amount"`
	ToAddress string `json:"to_address"`
}

type InternalTransferRequest struct {
	FromUserID string `json:"from_user_id"`
	ToUserID   string `json:"to_user_id"`
	Currency   string `json:"currency"`
	Amount     string `json:"amount"`
}

// ─── Wallet Service Implementation ───────────────────────────────────────────

type walletService struct {
	walletRepo WalletRepository
	txRepo     TransactionRepository
	cacheRepo  BalanceCacheRepository
	tatum      *tatum.Client
	cfg        config.TatumConfig
	firestore  *firestore.Client
}

func NewWalletService(
	walletRepo WalletRepository,
	txRepo TransactionRepository,
	cacheRepo BalanceCacheRepository,
	tatumClient *tatum.Client,
	cfg config.TatumConfig,
	fsClient *firestore.Client,
) WalletService {
	return &walletService{
		walletRepo: walletRepo,
		txRepo:     txRepo,
		cacheRepo:  cacheRepo,
		tatum:      tatumClient,
		cfg:        cfg,
		firestore:  fsClient,
	}
}

func (s *walletService) getChainName(currency string) (string, error) {
	if currency == "BTC" {
		return s.cfg.BTCChain, nil
	} else if currency == "ETH" {
		return s.cfg.ETHChain, nil
	}
	return "", fmt.Errorf("unsupported canonical currency: %s", currency)
}

func (s *walletService) CreateUserWallet(ctx context.Context, userId, currency string) (*Wallet, error) {
	if currency != "BTC" && currency != "ETH" {
		return nil, fmt.Errorf("invalid currency: %s", currency)
	}

	w, err := s.walletRepo.GetWalletByUserAndCurrency(ctx, userId, currency)
	if err == nil {
		return w, nil // Already exists
	} else if err != ErrWalletNotFound {
		return nil, err
	}

	chain, err := s.getChainName(currency)
	if err != nil {
		return nil, err
	}

	// Make sure master wallet exists
	master, err := s.walletRepo.GetMasterWallet(ctx, currency)
	if err != nil {
		// Initialize master wallet if not exists
		if status.Code(err) == codes.NotFound || err.Error() == "rpc error: code = NotFound desc = " {
            // Simplified error check
		}
		// In a real scenario, GenerateMasterWallet would be called here.
		// For safety and idempotency, we assume master wallets are pre-generated by admin,
		// but let's generate it if not found for seamless flow.
		res, genErr := s.tatum.GenerateMasterWallet(ctx, chain)
		if genErr != nil {
			return nil, fmt.Errorf("failed to generate master wallet: %w", genErr)
		}
		master = &MasterWallet{
			Currency:            currency,
			Network:             chain,
			Xpub:                res.Xpub,
			LastDerivationIndex: 0,
			CreatedAt:           time.Now(),
		}
		_ = s.walletRepo.CreateMasterWallet(ctx, master)
		// WARNING: mnemonic is not stored. It must be securely backed up by broker elsewhere.
	}

	nextIdx, err := s.walletRepo.GetNextDerivationIndex(ctx, currency)
	if err != nil {
		return nil, fmt.Errorf("failed to get next derivation index: %w", err)
	}

	address, err := s.tatum.DeriveAddress(ctx, chain, master.Xpub, nextIdx)
	if err != nil {
		return nil, fmt.Errorf("failed to derive address: %w", err)
	}

	tatumRefId, err := s.tatum.SubscribeAddressWebhook(ctx, chain, address)
	if err != nil {
		// Just log and continue, can retry subscription later
		fmt.Printf("warning: failed to subscribe webhook: %v\n", err)
	}

	newWallet := &Wallet{
		UserID:          userId,
		Currency:        currency,
		DepositAddress:  address,
		DerivationIndex: nextIdx,
		Balance:         "0",
		LockedBalance:   "0",
		Network:         chain,
		CreatedAt:       time.Now(),
		UpdatedAt:       time.Now(),
	}

	if err := s.walletRepo.CreateWallet(ctx, newWallet); err != nil {
		return nil, err
	}

	// We can save tatumRefId to a webhook_subscriptions collection if needed
	_ = tatumRefId

	return newWallet, nil
}

func (s *walletService) GetBalance(ctx context.Context, userId, currency string) (string, string, error) {
	bal, locked, err := s.cacheRepo.GetCachedBalance(ctx, userId, currency)
	if err == nil {
		return bal, locked, nil
	}
	if err != redis.Nil {
		return "0", "0", err
	}

	w, err := s.walletRepo.GetWalletByUserAndCurrency(ctx, userId, currency)
	if err != nil {
		return "0", "0", err
	}

	_ = s.cacheRepo.SetCachedBalance(ctx, userId, currency, w.Balance, w.LockedBalance, 5*time.Minute)
	return w.Balance, w.LockedBalance, nil
}

func (s *walletService) ProcessDeposit(ctx context.Context, payload WebhookPayload) error {
	exists, err := s.cacheRepo.ExistsIdempotencyKey(ctx, payload.TxId)
	if err != nil {
		return err
	}
	if exists {
		return ErrIdempotencyKeyFound
	}

	w, err := s.walletRepo.GetWalletByDepositAddress(ctx, payload.Address)
	if err != nil {
		return fmt.Errorf("wallet not found for address %s: %w", payload.Address, err)
	}

	// Check confirmations threshold
	requiredConf := 1
	if s.cfg.IsMainnet {
		if w.Currency == "BTC" {
			requiredConf = 3
		} else if w.Currency == "ETH" {
			requiredConf = 12
		}
	} else {
		if w.Currency == "ETH" {
			requiredConf = 2
		}
	}

	if payload.Confirmations < requiredConf {
		return fmt.Errorf("insufficient confirmations: %d < %d", payload.Confirmations, requiredConf)
	}

	// Atomic update in Firestore
	docId := fmt.Sprintf("%s_%s", w.UserID, w.Currency)
	docRef := s.firestore.Collection("wallets").Doc(docId)

	err = s.firestore.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
		doc, err := tx.Get(docRef)
		if err != nil {
			return err
		}
		var currentWallet Wallet
		if err := doc.DataTo(&currentWallet); err != nil {
			return err
		}

		currentBal, _ := new(big.Int).SetString(currentWallet.Balance, 10)
		if currentBal == nil {
			currentBal = big.NewInt(0)
		}
		depositAmount, _ := new(big.Int).SetString(payload.Amount, 10)
		if depositAmount == nil {
			return ErrInvalidAmount
		}

		newBal := new(big.Int).Add(currentBal, depositAmount)

		return tx.Update(docRef, []firestore.Update{
			{Path: "balance", Value: newBal.String()},
			{Path: "updated_at", Value: time.Now()},
		})
	})
	if err != nil {
		return err
	}

	_ = s.cacheRepo.InvalidateBalance(ctx, w.UserID, w.Currency)

	txRecord := &Transaction{
		ID:            uuid.New().String(),
		UserID:        w.UserID,
		Type:          TxTypeDeposit,
		Currency:      w.Currency,
		Network:       w.Network,
		Amount:        payload.Amount,
		Fee:           "0",
		Status:        TxStatusConfirmed,
		ToAddress:     payload.Address,
		TxHash:        payload.TxId,
		Confirmations: payload.Confirmations,
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}

	_ = s.txRepo.CreateTransaction(ctx, txRecord)
	_ = s.cacheRepo.SetIdempotencyKey(ctx, payload.TxId, 24*time.Hour)

	return nil
}

func (s *walletService) RequestWithdrawal(ctx context.Context, req WithdrawalRequest) (*Transaction, error) {
	w, err := s.walletRepo.GetWalletByUserAndCurrency(ctx, req.UserID, req.Currency)
	if err != nil {
		return nil, err
	}

	amountInt, _ := new(big.Int).SetString(req.Amount, 10)
	if amountInt == nil || amountInt.Sign() <= 0 {
		return nil, ErrInvalidAmount
	}

	// Atomic lock
	docId := fmt.Sprintf("%s_%s", req.UserID, req.Currency)
	docRef := s.firestore.Collection("wallets").Doc(docId)

	err = s.firestore.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
		doc, err := tx.Get(docRef)
		if err != nil {
			return err
		}
		var currentWallet Wallet
		if err := doc.DataTo(&currentWallet); err != nil {
			return err
		}

		bal, _ := new(big.Int).SetString(currentWallet.Balance, 10)
		if bal == nil {
			bal = big.NewInt(0)
		}
		locked, _ := new(big.Int).SetString(currentWallet.LockedBalance, 10)
		if locked == nil {
			locked = big.NewInt(0)
		}

		available := new(big.Int).Sub(bal, locked)
		if available.Cmp(amountInt) < 0 {
			return ErrInsufficientBalance
		}

		newLocked := new(big.Int).Add(locked, amountInt)
		return tx.Update(docRef, []firestore.Update{
			{Path: "locked_balance", Value: newLocked.String()},
			{Path: "updated_at", Value: time.Now()},
		})
	})
	if err != nil {
		return nil, err
	}
	_ = s.cacheRepo.InvalidateBalance(ctx, req.UserID, req.Currency)

	txRecord := &Transaction{
		ID:        uuid.New().String(),
		UserID:    req.UserID,
		Type:      TxTypeWithdrawal,
		Currency:  req.Currency,
		Network:   w.Network,
		Amount:    req.Amount,
		Fee:       "0", // Tatum usually takes fee from master wallet
		Status:    TxStatusPending,
		ToAddress: req.ToAddress,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	_ = s.txRepo.CreateTransaction(ctx, txRecord)

	// Send to Tatum
	var txHash string
	var tatumErr error

	if req.Currency == "BTC" {
		tatumReq := tatum.BTCSendRequest{
			FromAddress: []tatum.BTCFromAddress{
				{Address: "MASTER_ADDRESS_PLACEHOLDER", PrivateKey: s.cfg.BTCMasterPrivateKey},
			},
			To: []tatum.BTCTo{
				{Address: req.ToAddress, Value: float64(amountInt.Int64()) / 1e8}, // simplified formatting
			},
		}
		txHash, tatumErr = s.tatum.SendBTCTransaction(ctx, tatumReq)
	} else if req.Currency == "ETH" {
		tatumReq := tatum.ETHSendRequest{
			To:             req.ToAddress,
			Amount:         req.Amount, // assume wei string
			FromPrivateKey: s.cfg.ETHMasterPrivateKey,
		}
		txHash, tatumErr = s.tatum.SendETHTransaction(ctx, tatumReq)
	}

	if tatumErr != nil {
		// Unlock
		_ = s.firestore.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
			doc, _ := tx.Get(docRef)
			var currentWallet Wallet
			_ = doc.DataTo(&currentWallet)
			locked, _ := new(big.Int).SetString(currentWallet.LockedBalance, 10)
			newLocked := new(big.Int).Sub(locked, amountInt)
			return tx.Update(docRef, []firestore.Update{{Path: "locked_balance", Value: newLocked.String()}})
		})
		_ = s.cacheRepo.InvalidateBalance(ctx, req.UserID, req.Currency)

		_ = s.txRepo.UpdateTransactionStatus(ctx, txRecord.ID, TxStatusFailed, "")
		return txRecord, fmt.Errorf("failed to send transaction: %w", tatumErr)
	}

	// Success, deduct from locked and total balance
	_ = s.firestore.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
		doc, _ := tx.Get(docRef)
		var currentWallet Wallet
		_ = doc.DataTo(&currentWallet)
		
		bal, _ := new(big.Int).SetString(currentWallet.Balance, 10)
		locked, _ := new(big.Int).SetString(currentWallet.LockedBalance, 10)
		
		newBal := new(big.Int).Sub(bal, amountInt)
		newLocked := new(big.Int).Sub(locked, amountInt)
		
		return tx.Update(docRef, []firestore.Update{
			{Path: "balance", Value: newBal.String()},
			{Path: "locked_balance", Value: newLocked.String()},
			{Path: "updated_at", Value: time.Now()},
		})
	})
	_ = s.cacheRepo.InvalidateBalance(ctx, req.UserID, req.Currency)
	_ = s.txRepo.UpdateTransactionStatus(ctx, txRecord.ID, TxStatusConfirmed, txHash)
	
	txRecord.TxHash = txHash
	txRecord.Status = TxStatusConfirmed
	return txRecord, nil
}

// ─── Internal Transfer Service Implementation ────────────────────────────────

type internalTransferService struct {
	firestore *firestore.Client
	txRepo    TransactionRepository
	cacheRepo BalanceCacheRepository
}

func NewInternalTransferService(
	fsClient *firestore.Client,
	txRepo TransactionRepository,
	cacheRepo BalanceCacheRepository,
) InternalTransferService {
	return &internalTransferService{
		firestore: fsClient,
		txRepo:    txRepo,
		cacheRepo: cacheRepo,
	}
}

func (s *internalTransferService) Transfer(ctx context.Context, req InternalTransferRequest) (*Transaction, error) {
	amountInt, _ := new(big.Int).SetString(req.Amount, 10)
	if amountInt == nil || amountInt.Sign() <= 0 {
		return nil, ErrInvalidAmount
	}

	fromDocId := fmt.Sprintf("%s_%s", req.FromUserID, req.Currency)
	toDocId := fmt.Sprintf("%s_%s", req.ToUserID, req.Currency)
	
	fromRef := s.firestore.Collection("wallets").Doc(fromDocId)
	toRef := s.firestore.Collection("wallets").Doc(toDocId)

	err := s.firestore.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
		fromDoc, err := tx.Get(fromRef)
		if err != nil {
			return err
		}
		var fromWallet Wallet
		if err := fromDoc.DataTo(&fromWallet); err != nil {
			return err
		}

		toDoc, err := tx.Get(toRef)
		if err != nil {
			return err
		}
		var toWallet Wallet
		if err := toDoc.DataTo(&toWallet); err != nil {
			return err
		}

		fromBal, _ := new(big.Int).SetString(fromWallet.Balance, 10)
		if fromBal == nil { fromBal = big.NewInt(0) }
		fromLocked, _ := new(big.Int).SetString(fromWallet.LockedBalance, 10)
		if fromLocked == nil { fromLocked = big.NewInt(0) }
		
		available := new(big.Int).Sub(fromBal, fromLocked)
		if available.Cmp(amountInt) < 0 {
			return ErrInsufficientBalance
		}

		toBal, _ := new(big.Int).SetString(toWallet.Balance, 10)
		if toBal == nil { toBal = big.NewInt(0) }

		newFromBal := new(big.Int).Sub(fromBal, amountInt)
		newToBal := new(big.Int).Add(toBal, amountInt)

		if err := tx.Update(fromRef, []firestore.Update{
			{Path: "balance", Value: newFromBal.String()},
			{Path: "updated_at", Value: time.Now()},
		}); err != nil {
			return err
		}

		return tx.Update(toRef, []firestore.Update{
			{Path: "balance", Value: newToBal.String()},
			{Path: "updated_at", Value: time.Now()},
		})
	})
	
	if err != nil {
		return nil, err
	}

	_ = s.cacheRepo.InvalidateBalance(ctx, req.FromUserID, req.Currency)
	_ = s.cacheRepo.InvalidateBalance(ctx, req.ToUserID, req.Currency)

	txDebit := &Transaction{
		ID:        uuid.New().String(),
		UserID:    req.FromUserID,
		Type:      TxTypeInternal,
		Currency:  req.Currency,
		Amount:    "-" + req.Amount,
		Status:    TxStatusConfirmed,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	_ = s.txRepo.CreateTransaction(ctx, txDebit)

	txCredit := &Transaction{
		ID:        uuid.New().String(),
		UserID:    req.ToUserID,
		Type:      TxTypeInternal,
		Currency:  req.Currency,
		Amount:    req.Amount,
		Status:    TxStatusConfirmed,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	_ = s.txRepo.CreateTransaction(ctx, txCredit)

	return txDebit, nil
}
